services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - ecommerce-network

  app:
    image: java-ecommerce:latest
    container_name: java-ecommerce
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network

  jenkins:
    build: ./jenkins
    container_name: jenkins
    ports:
      - "8090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /Users/nagarjunar/Java-Ecommerce-New:/var/jenkins_home/project
      - /Users/nagarjunar/.m2:/var/jenkins_home/.m2
    networks:
      - ecommerce-network
    depends_on:
      - sonarqube

networks:
  ecommerce-network:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  jenkins_home: